# Generated by Django 2.0 on 2021-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10, unique=True)),
                ('u_gender', models.CharField(max_length=4)),
                ('u_email', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=20)),
                ('u_longitude', models.CharField(max_length=20)),
                ('u_latitude', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
